In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load in combined dataset
df = pd.read_csv('../../data/concat_data.csv')
df

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
0,PacificWest,PacificWest,NaN,True,NaN,NaN,False,1800000.0,1114761060,realtorjinheechoi@hotmail.com,...,NaN,7740.0,1.0,False,3.0,Fullerton Joint Union High,92833,310.0,7740.0,NaN
1,Malibu,Malibu,"Tile,Wood",True,NaN,True,False,1200000.0,1114760473,sonia@maisonrealestate.com,...,38x123,4697.0,NaN,False,2.0,NaN,90065,NaN,4697.0,NaN
2,Mlslistings,Mlslistings,"Carpet,Laminate",False,NaN,NaN,NaN,NaN,1114744790,dthurro@thurrorealty.com,...,NaN,5775.0,NaN,False,1.0,Other,95014,NaN,5775.0,NaN
3,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,False,1425000.0,1114743101,apreston@grandavenueca.com,...,NaN,7500.0,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,124.0,7500.0,NaN
4,SanDiego,SanDiego,NaN,False,NaN,NaN,False,660000.0,1114741523,dave.advent@yahoo.com,...,NaN,4552.0,NaN,False,2.0,NaN,92026,NaN,4552.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69223,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,False,NaN,NaN,False,563490.0,1114519790,sold@myattrealestate.com,...,NaN,6900.0,4.0,True,3.0,Hesperia Unified,92345,157.0,300564000.0,NaN
69224,Southland,Southland,"Carpet,SeeRemarks,Tile",True,NaN,NaN,False,920000.0,1114519708,tony@tonyashdown.com,...,NaN,15996.0,1.0,False,3.0,William S. Hart Union,91387,169.0,15996.0,NaN
69225,OrangeCounty,OrangeCounty,"Carpet,Laminate",False,NaN,NaN,False,3000000.0,1114518593,victoriaxia777@Gmail.com,...,NaN,4500.0,1.0,False,2.0,Irvine Unified,92618,389.0,4500.0,NaN
69226,PacificWest,PacificWest,NaN,True,NaN,NaN,False,1499000.0,1114518520,claudiorealtor01@gmail.com,...,NaN,24829.0,3.0,False,8.0,Riverside Unified,92503,0.0,24829.0,NaN
69227,PasadenaFoothills,PasadenaFoothills,"Tile,Wood",False,NaN,NaN,False,860000.0,1114517247,shanshan.lin@compass.com,...,NaN,6353.0,NaN,NaN,2.0,NaN,91040,NaN,6353.0,NaN

Our group decided to only use LotSizeSquareFeet so I dropped the other related columns. I also removed columns containing names, email addresses, or office information because these features are unlikely to be informative for predicting listing closing prices.

In [3]:
# Drop irrelevant columns

drop = ['BuyerAgentAOR', 'ListAgentAOR', 'OriginalListPrice', 'ListAgentFirstName', 'ListAgentLastName',
       'ListAgentEmail', 'CoListAgentFirstName', 'CoListOfficeName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerOfficeName', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'BuyerOfficeAOR', 'CoBuyerAgentFirstName', 'ListAgentFullName', 'ListOfficeName', 
       'LotSizeDimensions', 'LotSizeAcres', 'LotSizeArea', 'BuildingAreaTotal', 'ListPrice', 'OriginalListPrice']

df = df.drop(columns=drop)
df.head()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,...,HighSchool,Levels,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
0,NaN,True,NaN,NaN,False,1114761060,2025-05-29,1800000.0,33.899427,-117.977995,...,NaN,Two,1.0,False,3.0,Fullerton Joint Union High,92833,310.0,7740.0,NaN
1,"Tile,Wood",True,NaN,True,False,1114760473,2025-05-19,1200000.0,34.095980,-118.221993,...,NaN,One,NaN,False,2.0,NaN,90065,NaN,4697.0,NaN
2,"Carpet,Laminate",False,NaN,NaN,NaN,1114744790,2025-05-27,2250000.0,37.313093,-122.006414,...,NaN,NaN,NaN,False,1.0,Other,95014,NaN,5775.0,NaN
3,NaN,True,NaN,NaN,False,1114743101,2025-05-30,1425000.0,33.884526,-117.778002,...,NaN,One,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,124.0,7500.0,NaN
4,NaN,False,NaN,NaN,False,1114741523,2025-05-30,660000.0,33.169703,-117.081580,...,NaN,Two,NaN,False,2.0,NaN,92026,NaN,4552.0,NaN

In [4]:
# Identify the proportion and number of null values for each column

def create_info_df(df):
    df_info = pd.DataFrame()
    df_info['prop_null'] = df.isna().sum()/len(df)
    df_info['num_null'] = df.isna().sum()
    df_info['data_types'] = df.dtypes
    return df_info.sort_values(by='prop_null', ascending=False)

create_info_df(df)

                              prop_null  num_null data_types
MiddleOrJuniorSchoolDistrict   1.000000     69228    float64
TaxAnnualAmount                1.000000     69228    float64
AboveGradeFinishedArea         1.000000     69228    float64
FireplacesTotal                1.000000     69228    float64
TaxYear                        1.000000     69228    float64
ElementarySchoolDistrict       1.000000     69228    float64
CoveredSpaces                  1.000000     69228    float64
BusinessType                   1.000000     69228    float64
WaterfrontYN                   0.999509     69194     object
BelowGradeFinishedArea         0.992893     68736    float64
BasementYN                     0.975790     67552     object
BuilderName                    0.955033     66115        str
ElementarySchool               0.865921     59946        str
MiddleOrJuniorSchool           0.864448     59844        str
HighSchool                     0.824522     57080        str
AssociationFeeFrequency        0.752542     52097        str
SubdivisionName                0.644595     44624        str
MainLevelBedrooms              0.394768     27329    float64
Flooring                       0.348573     24131        str
AssociationFee                 0.298217     20645    float64
HighSchoolDistrict             0.270888     18753        str
MLSAreaMajor                   0.151254     10471        str
AttachedGarageYN               0.120298      8328     object
Stories                        0.103542      7168    float64
ViewYN                         0.095496      6611     object
NewConstructionYN              0.077353      5355     object
PoolPrivateYN                  0.076819      5318     object
Levels                         0.070564      4885        str
GarageSpaces                   0.040605      2811    float64
LotSizeSquareFeet              0.017218      1192    float64
StreetNumberNumeric            0.000924        64    float64
YearBuilt                      0.000780        54    float64
UnparsedAddress                0.000737        51        str
FireplaceYN                    0.000621        43     object
LivingArea                     0.000607        42    float64
City                           0.000506        35        str
BathroomsTotalInteger          0.000173        12    float64
PurchaseContractDate           0.000043         3        str
Longitude                      0.000043         3    float64
Latitude                       0.000043         3    float64
PostalCode                     0.000014         1        str
ParkingTotal                   0.000014         1    float64
BedroomsTotal                  0.000000         0    float64
MlsStatus                      0.000000         0        str
ListingKeyNumeric              0.000000         0      int64
DaysOnMarket                   0.000000         0      int64
PropertySubType                0.000000         0        str
ContractStatusChangeDate       0.000000         0        str
ListingId                      0.000000         0        str
CountyOrParish                 0.000000         0        str
PropertyType                   0.000000         0        str
CloseDate                      0.000000         0        str
ClosePrice                     0.000000         0    float64
StateOrProvince                0.000000         0        str
ListingContractDate            0.000000         0        str
ListingKey                     0.000000         0      int64

Based on these proportions, I chose to drop columns with at least 95% missing values. Since fewer than 5% of the entries in these columns contain data, they are unlikely to contribute meaningful predictive information, and most values would effectively be treated as unknown.

In [5]:
# Drop columns with a proportion of 95% or more missing values

drop = ['MiddleOrJuniorSchoolDistrict', 'TaxAnnualAmount', 'CoveredSpaces',
       'BusinessType', 'ElementarySchoolDistrict', 'FireplacesTotal',
       'TaxYear', 'AboveGradeFinishedArea', 'WaterfrontYN',
       'BelowGradeFinishedArea', 'BasementYN', 'BuilderName']
df = df.drop(columns=drop)
df

,Flooring,ViewYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,...,Stories,HighSchool,Levels,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet
0,NaN,True,False,1114761060,2025-05-29,1800000.0,33.899427,-117.977995,2856 Muir Trail Drive,Residential,...,2.0,NaN,Two,1.0,False,3.0,Fullerton Joint Union High,92833,310.0,7740.0
1,"Tile,Wood",True,False,1114760473,2025-05-19,1200000.0,34.095980,-118.221993,1050 Del Rio Avenue,Residential,...,1.0,NaN,One,NaN,False,2.0,NaN,90065,NaN,4697.0
2,"Carpet,Laminate",False,NaN,1114744790,2025-05-27,2250000.0,37.313093,-122.006414,10672 Johansen Drive,Residential,...,NaN,NaN,NaN,NaN,False,1.0,Other,95014,NaN,5775.0
3,NaN,True,False,1114743101,2025-05-30,1425000.0,33.884526,-117.778002,5305 Via Cartagena,Residential,...,1.0,NaN,One,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,124.0,7500.0
4,NaN,False,False,1114741523,2025-05-30,660000.0,33.169703,-117.081580,2422 Lake Forest St,Residential,...,2.0,NaN,Two,NaN,False,2.0,NaN,92026,NaN,4552.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69223,NaN,False,False,1114519790,2025-10-01,585522.0,34.368013,-117.278705,17626 Crabtree Meadows,Residential,...,1.0,NaN,One,4.0,True,3.0,Hesperia Unified,92345,157.0,300564000.0
69224,"Carpet,SeeRemarks,Tile",True,False,1114519708,2025-10-22,899000.0,34.428858,-118.437668,17334 Sierra Sunrise Lane,Residential,...,2.0,NaN,Two,1.0,False,3.0,William S. Hart Union,91387,169.0,15996.0
69225,"Carpet,Laminate",False,False,1114518593,2025-10-09,2610000.0,33.682858,-117.714011,62 Pelican Lane,Residential,...,NaN,NaN,ThreeOrMore,1.0,False,2.0,Irvine Unified,92618,389.0,4500.0
69226,NaN,True,False,1114518520,2025-10-14,1100000.0,33.884064,-117.410457,14461 Oakley Drive,Residential,...,2.0,NaN,Two,3.0,False,8.0,Riverside Unified,92503,0.0,24829.0
69227,"Tile,Wood",False,False,1114517247,2025-10-10,845000.0,34.256390,-118.320853,10316 Newhome Avenue,Residential,...,1.0,NaN,One,NaN,NaN,2.0,NaN,91040,NaN,6353.0

In [6]:
create_info_df(df)

                          prop_null  num_null data_types
ElementarySchool           0.865921     59946        str
MiddleOrJuniorSchool       0.864448     59844        str
HighSchool                 0.824522     57080        str
AssociationFeeFrequency    0.752542     52097        str
SubdivisionName            0.644595     44624        str
MainLevelBedrooms          0.394768     27329    float64
Flooring                   0.348573     24131        str
AssociationFee             0.298217     20645    float64
HighSchoolDistrict         0.270888     18753        str
MLSAreaMajor               0.151254     10471        str
AttachedGarageYN           0.120298      8328     object
Stories                    0.103542      7168    float64
ViewYN                     0.095496      6611     object
NewConstructionYN          0.077353      5355     object
PoolPrivateYN              0.076819      5318     object
Levels                     0.070564      4885        str
GarageSpaces               0.040605      2811    float64
LotSizeSquareFeet          0.017218      1192    float64
StreetNumberNumeric        0.000924        64    float64
YearBuilt                  0.000780        54    float64
UnparsedAddress            0.000737        51        str
FireplaceYN                0.000621        43     object
LivingArea                 0.000607        42    float64
City                       0.000506        35        str
BathroomsTotalInteger      0.000173        12    float64
Latitude                   0.000043         3    float64
Longitude                  0.000043         3    float64
PurchaseContractDate       0.000043         3        str
PostalCode                 0.000014         1        str
ParkingTotal               0.000014         1    float64
ListingKey                 0.000000         0      int64
CloseDate                  0.000000         0        str
ClosePrice                 0.000000         0    float64
PropertyType               0.000000         0        str
MlsStatus                  0.000000         0        str
DaysOnMarket               0.000000         0      int64
ListingContractDate        0.000000         0        str
ContractStatusChangeDate   0.000000         0        str
BedroomsTotal              0.000000         0    float64
ListingId                  0.000000         0        str
ListingKeyNumeric          0.000000         0      int64
CountyOrParish             0.000000         0        str
PropertySubType            0.000000         0        str
StateOrProvince            0.000000         0        str

#### Dealing with Missing Values
- Drop null rows in columns with less than 5 missing values
- Fill NAs in categorical columns with 'Unknown'
- Flag missingness in rows where imputation was used
- Use median imputation or a missingness flag for numerical-categorical columns to preserve datatypes
- Assume that a missing value in a boolean column means False and fill accordingly
- Use median imputation on numerical rows to avoid outlier skew
- Assume missing `AssociationFee`, `GarageSpaces`, and `ParkingTotal` mean 0 and fill accordingly
- Drop columns with 0 values in `ClosePrice`, `LivingArea`, `BathroomsTotalInteger`, and `DaysOnMarket` as a 0 value is highly improbable

In [7]:
# Categorize columns

cat_col = ['Flooring', 'UnparsedAddress', 'AssociationFeeFrequency', 
        'MLSAreaMajor', 'ElementarySchool', 'SubdivisionName', 'City', 
        'PurchaseContractDate', 'MiddleOrJuniorSchool', 'HighSchool',
        'HighSchoolDistrict', 'PostalCode', 'Levels', 'ListingKey', 'CloseDate', 
        'PropertyType', 'ListingKeyNumeric', 'CountyOrParish', 'MlsStatus', 
        'PropertySubType', 'ListingId', 'ContractStatusChangeDate',
        'ListingContractDate', 'StateOrProvince' ]

bool_col = ['ViewYN', 'PoolPrivateYN', 'AttachedGarageYN', 'FireplaceYN', 'NewConstructionYN']

num_col = ['LivingArea', 'BuildingAreaTotal', 'LotSizeSquareFeet', 'ListPrice', 
            'BathroomsTotalInteger', 'Stories', 'MainLevelBedrooms', 'BedroomsTotal', 'DaysOnMarket']

In [8]:
# Drop null rows in columns with a very small number of missing values 
df = df.dropna(subset = ['PostalCode', 'ParkingTotal', 'Longitude', 'Latitude'])

# Fill missing categorical values with 'Unknown'
df[cat_col] = df[cat_col].fillna('Unknown')

# Flag missingness in columns where imputation is used
for col in df.columns:
    if df[col].isna().sum() > 0:
        df[f'{col}_was_missing'] = df[col].isna().astype(int) # 1 for missing, 0 for present

# Handle numerical-categorical columns with median or a specific numeric flag (like -1)
df['YearBuilt'] = df['YearBuilt'].fillna(df['YearBuilt'].median())
df['Latitude'] = df['Latitude'].fillna(df['Latitude'].median())
df['Longitude'] = df['Longitude'].fillna(df['Longitude'].median())
df['StreetNumberNumeric'] = df['StreetNumberNumeric'].fillna(-1)

# Convert to boolean type and fill NaNs with False
df[bool_col] = df[bool_col].fillna(False).astype(bool)

# Impute with the median value of the column
for col in num_col:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

# Special case: AssociationFee
# If an association fee is missing, it usually means there is no HOA fee (0.0)
if 'AssociationFee' in df.columns:
    df['AssociationFee'] = df['AssociationFee'].fillna(0.0)

# Fill missing parking/garage counts with 0
for col in ['GarageSpaces', 'ParkingTotal']:
    if col in df.columns:
        df[col] = df[col].fillna(0)

df = df[(df["ClosePrice"]>0) & (df["LivingArea"]>0) & (df["BathroomsTotalInteger"]>0) & (df["DaysOnMarket"]>0)]
df.head()

,Flooring,ViewYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,...,YearBuilt_was_missing,StreetNumberNumeric_was_missing,BathroomsTotalInteger_was_missing,FireplaceYN_was_missing,Stories_was_missing,MainLevelBedrooms_was_missing,NewConstructionYN_was_missing,GarageSpaces_was_missing,AssociationFee_was_missing,LotSizeSquareFeet_was_missing
11,"Tile,Wood",False,False,1114722526,2025-05-23,1344000.0,37.893054,-122.086327,Unknown,Residential,...,0,1,0,0,0,1,0,0,1,0
20,"Carpet,Stone,Wood",True,True,1114680429,2025-05-05,2175000.0,34.129941,-118.426100,13438 Java Drive,Residential,...,0,0,0,0,0,1,0,1,1,0
23,Unknown,False,False,1114670553,2025-05-29,5975000.0,34.135406,-118.118478,1538 E California Boulevard,Residential,...,0,0,0,0,0,1,0,1,1,0
26,"Carpet,Tile,Wood",False,False,1114650212,2025-05-28,1900000.0,34.037751,-118.395258,2807 Cardiff Avenue,Residential,...,0,0,0,0,0,1,0,1,1,0
42,"Carpet,Laminate",False,False,1114573617,2025-05-27,640000.0,34.247108,-118.428730,13535 Goleta Street,Residential,...,0,0,0,0,0,1,0,1,1,0

#### Encoding Columns
- Convert boolean columns to int values of 0 and 1
- Columns `Flooring` and `Levels` contained lists of values, use MultiLabelBinarizer to encode them
- Map ordinal values of `AssociationFeeFrequency` to their corresponding numerical values
- One hot encode a set of critical categorical columns instead of all to reduce column amount

In [9]:
# Encode Boolean columns
encode_df = df.copy()
encode_df[bool_col] = encode_df[bool_col].astype(int)

# Encode 'Flooring' and 'Levels' columns using MultiLabelBinarizer
from sklearn.preprocessing import MultiLabelBinarizer

cols = ['Flooring', 'Levels']
for col in cols:
    encode_df[col] = encode_df[col].str.split(',')
    mlb = MultiLabelBinarizer()
    encoded = pd.DataFrame(mlb.fit_transform(df[col]), columns=[f'{col}_{c}' for c in mlb.classes_], index=df.index)
    encode_df = encode_df.join(encoded)
    encode_df = encode_df.drop(columns = col)

# Map the ordinal values in 'AssociationFeeFrequency' to their associated numerical values
mapping = {
    'Unknown': 0,
    'Monthly': 1,
    'Quarterly': 2,
    'SemiAnnually': 3,
    'Annually': 4
}
encode_df['AssociationFeeFrequency'] = encode_df['AssociationFeeFrequency'].map(mapping)

# One hot encode subset of critical categorical columns
one_hot = ['CountyOrParish', 'StateOrProvince', 'City', 'PropertyType', 'PropertySubType', 'MlsStatus']
encode_df = pd.get_dummies(encode_df, columns=[col for col in one_hot if col in encode_df.columns], drop_first=True)

df = encode_df
df.head()

,ViewYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,LivingArea,DaysOnMarket,...,City_Wrightwood,City_Yermo,City_Yorba Linda,City_Yorkville,City_Yosemite,City_Yountville,City_Yreka,City_Yuba City,City_Yucaipa,City_Yucca Valley
11,0,0,1114722526,2025-05-23,1344000.0,37.893054,-122.086327,Unknown,1278.0,1,...,False,False,False,False,False,False,False,False,False,False
20,1,1,1114680429,2025-05-05,2175000.0,34.129941,-118.426100,13438 Java Drive,2247.0,18,...,False,False,False,False,False,False,False,False,False,False
23,0,0,1114670553,2025-05-29,5975000.0,34.135406,-118.118478,1538 E California Boulevard,3993.0,1,...,False,False,False,False,False,False,False,False,False,False
26,0,0,1114650212,2025-05-28,1900000.0,34.037751,-118.395258,2807 Cardiff Avenue,1829.0,2,...,False,False,False,False,False,False,False,False,False,False
42,0,0,1114573617,2025-05-27,640000.0,34.247108,-118.428730,13535 Goleta Street,1440.0,62,...,False,False,False,False,False,False,False,False,False,False

#### Standardizing Numerical Values

Looking at our continuous numerical features, the scales vary drastically from one column to the next. Leaving the data with these massive differences in ranges can cause the final model to not make the most accurate predictions. To fix this and boost our overall model performance, I standardized the continuous variables so they're all evaluated on the same scale.

In [10]:
# Standardize continuous numerical columns

from sklearn.preprocessing import StandardScaler

scale = [
    "LivingArea",
    "LotSizeSquareFeet",
    "AssociationFee",
    "DaysOnMarket"
]

scaler = StandardScaler()
df[scale] = scaler.fit_transform(df[scale])
df.head()

,ViewYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,LivingArea,DaysOnMarket,...,City_Wrightwood,City_Yermo,City_Yorba Linda,City_Yorkville,City_Yosemite,City_Yountville,City_Yreka,City_Yuba City,City_Yucaipa,City_Yucca Valley
11,0,0,1114722526,2025-05-23,1344000.0,37.893054,-122.086327,Unknown,-0.737558,-0.798868,...,False,False,False,False,False,False,False,False,False,False
20,1,1,1114680429,2025-05-05,2175000.0,34.129941,-118.426100,13438 Java Drive,0.208885,-0.424176,...,False,False,False,False,False,False,False,False,False,False
23,0,0,1114670553,2025-05-29,5975000.0,34.135406,-118.118478,1538 E California Boulevard,1.914240,-0.798868,...,False,False,False,False,False,False,False,False,False,False
26,0,0,1114650212,2025-05-28,1900000.0,34.037751,-118.395258,2807 Cardiff Avenue,-0.199385,-0.776827,...,False,False,False,False,False,False,False,False,False,False
42,0,0,1114573617,2025-05-27,640000.0,34.247108,-118.428730,13535 Goleta Street,-0.579329,0.545616,...,False,False,False,False,False,False,False,False,False,False

In [11]:
smaller_df = df.iloc[0:100]
smaller_df.to_csv('02_cleaned.csv', index=False)

In [ ]:
# Convert CloseDate to datetime
df['CloseDate'] = pd.to_datetime(df['CloseDate'])
df = df.sort_values('CloseDate').reset_index(drop=True)

# Split dataframe into train and test sets using given window
def get_time_split(data, X_months):
    latest_date = data['CloseDate'].max()
    test_start_date = latest_date - pd.DateOffset(months=1)
    train_start_date = test_start_date - pd.DateOffset(months=X_months)
    test_set = data[data['CloseDate'] >= test_start_date]
    train_set = data[(data['CloseDate'] >= train_start_date) & (data['CloseDate'] < test_start_date)]
    return train_set, test_set

# Create testing and training sets, removing target and 'CloseDate'
train_df, test_df = get_time_split(df, X_months=6)
target = 'ClosePrice'
X_train = train_df.drop(columns=['ClosePrice', 'CloseDate'])
y_train = train_df[target]
X_test = test_df.drop(columns=['ClosePrice', 'CloseDate'])
y_test = test_df[target]

# When modeling, different testing windows will be evaulated
# window_options = [3, 6, 12]
# for X in window_options:
#     train_df, test_df = get_time_split(df, X_months=X)
    
#     print(f"--- Experimenting with X = {X} Months ---")
#     print(f"Train Date Range: {train_df['CloseDate'].min().strftime('%Y-%m-%d')} to {train_df['CloseDate'].max().strftime('%Y-%m-%d')} ({len(train_df)} rows)")
#     print(f"Test Date Range:  {test_df['CloseDate'].min().strftime('%Y-%m-%d')} to {test_df['CloseDate'].max().strftime('%Y-%m-%d')} ({len(test_df)} rows)\n")