In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Load in combined dataset
df = pd.read_csv('../../data/concat_data.csv')
df

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
0,PacificWest,PacificWest,NaN,True,NaN,NaN,False,1800000.0,1114761060,realtorjinheechoi@hotmail.com,...,NaN,7740.00,1.0,False,3.0,Fullerton Joint Union High,92833,310.0,7740.0,NaN
1,Malibu,Malibu,"Tile,Wood",True,NaN,True,False,1200000.0,1114760473,sonia@maisonrealestate.com,...,38x123,4697.00,NaN,False,2.0,NaN,90065,NaN,4697.0,NaN
2,Mlslistings,Mlslistings,"Carpet,Laminate",False,NaN,NaN,NaN,NaN,1114744790,dthurro@thurrorealty.com,...,NaN,5775.00,NaN,False,1.0,Other,95014,NaN,5775.0,NaN
3,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,False,1425000.0,1114743101,apreston@grandavenueca.com,...,NaN,7500.00,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,124.0,7500.0,NaN
4,SanDiego,SanDiego,NaN,False,NaN,NaN,False,660000.0,1114741523,dave.advent@yahoo.com,...,NaN,4552.00,NaN,False,2.0,NaN,92026,NaN,4552.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141992,PacificWest,PacificWest,NaN,False,NaN,NaN,False,800000.0,1065799115,khwjenterprise@gmail.com,...,NaN,2921.00,2.0,False,0.0,Long Beach Unified,90813,0.0,2921.0,NaN
141993,NaN,VenturaCoastal,Wood,True,NaN,NaN,False,3500000.0,1063517703,ggoodmanrealty@aol.com,...,71.57,71.57,NaN,False,2.0,NaN,93060,NaN,3117589.2,NaN
141994,Southland,Southland,Wood,True,NaN,NaN,False,675000.0,1052367803,miguelcastellanosrealtor@gmail.com,...,NaN,7039.00,3.0,False,2.0,Los Angeles Unified,91345,0.0,7039.0,NaN
141995,ContraCosta,ContraCosta,"Carpet,SeeRemarks,Stone,Wood",NaN,NaN,True,False,35000000.0,1048618285,taso@ggsir.com,...,NaN,935669.00,NaN,False,24.0,NaN,94507,3039.0,935669.0,NaN
141996,RanchoSoutheast,RanchoSoutheast,NaN,False,NaN,NaN,False,369000.0,497817474,roylman@aol.com,...,NaN,5202.00,2.0,False,0.0,Los Angeles Unified,90003,0.0,5202.0,NaN

Our group decided to only use LotSizeSquareFeet so I dropped the other related columns. I also removed columns containing names, email addresses, or office information because these features are unlikely to be informative for predicting listing closing prices. I also dropped duplicates.

In [5]:
# Drop irrelevant columns

drop = ['BuyerAgentAOR', 'ListAgentAOR', 'OriginalListPrice', 'ListAgentFirstName', 'ListAgentLastName',
       'ListAgentEmail', 'CoListAgentFirstName', 'CoListOfficeName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerOfficeName', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'BuyerOfficeAOR', 'CoBuyerAgentFirstName', 'ListAgentFullName', 'ListOfficeName', 
       'LotSizeDimensions', 'LotSizeAcres', 'LotSizeArea', 'BuildingAreaTotal', 'ListPrice', 'OriginalListPrice']

df = df.drop(columns=drop)
df = df.drop_duplicates()
df.head()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,...,HighSchool,Levels,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
0,NaN,True,NaN,NaN,False,1114761060,2025-05-29,1800000.0,33.899427,-117.977995,...,NaN,Two,1.0,False,3.0,Fullerton Joint Union High,92833,310.0,7740.0,NaN
1,"Tile,Wood",True,NaN,True,False,1114760473,2025-05-19,1200000.0,34.095980,-118.221993,...,NaN,One,NaN,False,2.0,NaN,90065,NaN,4697.0,NaN
2,"Carpet,Laminate",False,NaN,NaN,NaN,1114744790,2025-05-27,2250000.0,37.313093,-122.006414,...,NaN,NaN,NaN,False,1.0,Other,95014,NaN,5775.0,NaN
3,NaN,True,NaN,NaN,False,1114743101,2025-05-30,1425000.0,33.884526,-117.778002,...,NaN,One,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,124.0,7500.0,NaN
4,NaN,False,NaN,NaN,False,1114741523,2025-05-30,660000.0,33.169703,-117.081580,...,NaN,Two,NaN,False,2.0,NaN,92026,NaN,4552.0,NaN

In [6]:
# Identify the proportion and number of null values for each column

def create_info_df(df):
    df_info = pd.DataFrame()
    df_info['prop_null'] = df.isna().sum()/len(df)
    df_info['num_null'] = df.isna().sum()
    df_info['data_types'] = df.dtypes
    return df_info.sort_values(by='prop_null', ascending=False)

create_info_df(df)

                              prop_null  num_null data_types
MiddleOrJuniorSchoolDistrict   1.000000    141989    float64
TaxAnnualAmount                1.000000    141989    float64
AboveGradeFinishedArea         1.000000    141989    float64
FireplacesTotal                1.000000    141989    float64
TaxYear                        1.000000    141989    float64
ElementarySchoolDistrict       1.000000    141989    float64
CoveredSpaces                  1.000000    141989    float64
BusinessType                   1.000000    141989    float64
WaterfrontYN                   0.999486    141916     object
BelowGradeFinishedArea         0.992816    140969    float64
BasementYN                     0.975815    138555     object
BuilderName                    0.954461    135523        str
ElementarySchool               0.869694    123487        str
MiddleOrJuniorSchool           0.868631    123336        str
HighSchool                     0.828592    117651        str
AssociationFeeFrequency        0.745445    105845        str
SubdivisionName                0.645726     91686        str
MainLevelBedrooms              0.391382     55572    float64
Flooring                       0.355950     50541        str
AssociationFee                 0.291283     41359    float64
HighSchoolDistrict             0.269535     38271        str
MLSAreaMajor                   0.146561     20810        str
AttachedGarageYN               0.121073     17191     object
Stories                        0.104043     14773    float64
ViewYN                         0.090859     12901     object
PoolPrivateYN                  0.077309     10977     object
NewConstructionYN              0.076274     10830     object
Levels                         0.071928     10213        str
GarageSpaces                   0.039552      5616    float64
LotSizeSquareFeet              0.017121      2431    float64
StreetNumberNumeric            0.001183       168    float64
UnparsedAddress                0.000972       138        str
FireplaceYN                    0.000761       108     object
YearBuilt                      0.000683        97    float64
LivingArea                     0.000549        78    float64
City                           0.000345        49        str
BathroomsTotalInteger          0.000092        13    float64
Longitude                      0.000092        13    float64
Latitude                       0.000092        13    float64
PurchaseContractDate           0.000049         7        str
PostalCode                     0.000014         2        str
ParkingTotal                   0.000007         1    float64
ListingContractDate            0.000000         0        str
StateOrProvince                0.000000         0        str
ClosePrice                     0.000000         0    float64
CloseDate                      0.000000         0        str
CountyOrParish                 0.000000         0        str
ContractStatusChangeDate       0.000000         0        str
ListingKey                     0.000000         0      int64
ListingId                      0.000000         0        str
PropertyType                   0.000000         0        str
PropertySubType                0.000000         0        str
DaysOnMarket                   0.000000         0      int64
ListingKeyNumeric              0.000000         0      int64
MlsStatus                      0.000000         0        str
BedroomsTotal                  0.000000         0    float64

Based on these proportions, I chose to drop columns with at least 95% missing values. Since fewer than 5% of the entries in these columns contain data, they are unlikely to contribute meaningful predictive information, and most values would effectively be treated as unknown.

In [7]:
# Drop columns with a proportion of 95% or more missing values

drop = ['MiddleOrJuniorSchoolDistrict', 'TaxAnnualAmount', 'CoveredSpaces',
       'BusinessType', 'ElementarySchoolDistrict', 'FireplacesTotal',
       'TaxYear', 'AboveGradeFinishedArea', 'WaterfrontYN',
       'BelowGradeFinishedArea', 'BasementYN', 'BuilderName']
df = df.drop(columns=drop)
df

,Flooring,ViewYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,...,Stories,HighSchool,Levels,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet
0,NaN,True,False,1114761060,2025-05-29,1800000.0,33.899427,-117.977995,2856 Muir Trail Drive,Residential,...,2.0,NaN,Two,1.0,False,3.0,Fullerton Joint Union High,92833,310.0,7740.0
1,"Tile,Wood",True,False,1114760473,2025-05-19,1200000.0,34.095980,-118.221993,1050 Del Rio Avenue,Residential,...,1.0,NaN,One,NaN,False,2.0,NaN,90065,NaN,4697.0
2,"Carpet,Laminate",False,NaN,1114744790,2025-05-27,2250000.0,37.313093,-122.006414,10672 Johansen Drive,Residential,...,NaN,NaN,NaN,NaN,False,1.0,Other,95014,NaN,5775.0
3,NaN,True,False,1114743101,2025-05-30,1425000.0,33.884526,-117.778002,5305 Via Cartagena,Residential,...,1.0,NaN,One,3.0,False,2.0,Placentia-Yorba Linda Unified,92886,124.0,7500.0
4,NaN,False,False,1114741523,2025-05-30,660000.0,33.169703,-117.081580,2422 Lake Forest St,Residential,...,2.0,NaN,Two,NaN,False,2.0,NaN,92026,NaN,4552.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141992,NaN,False,False,1065799115,2026-05-07,455000.0,33.786867,-118.187745,1584 Elm Avenue,Residential,...,1.0,NaN,One,2.0,False,0.0,Long Beach Unified,90813,0.0,2921.0
141993,Wood,True,False,1063517703,2026-05-08,1850000.0,34.377680,-119.145860,6770 Wheeler Canyon Road,Residential,...,1.0,NaN,One,NaN,False,2.0,NaN,93060,NaN,3117589.2
141994,Wood,True,False,1052367803,2026-05-06,655000.0,34.275262,-118.452369,14655 Maclay Street,Residential,...,1.0,San Fernando,One,3.0,False,2.0,Los Angeles Unified,91345,0.0,7039.0
141995,"Carpet,SeeRemarks,Stone,Wood",NaN,False,1048618285,2026-05-15,21500000.0,37.854648,-121.961587,7 Country Oak Ln,Residential,...,NaN,NaN,ThreeOrMore,NaN,False,24.0,NaN,94507,3039.0,935669.0
141996,NaN,False,False,497817474,2026-05-21,410000.0,33.960793,-118.271277,214 E 85th Street,Residential,...,1.0,NaN,One,2.0,False,0.0,Los Angeles Unified,90003,0.0,5202.0

In [8]:
create_info_df(df)

                          prop_null  num_null data_types
ElementarySchool           0.869694    123487        str
MiddleOrJuniorSchool       0.868631    123336        str
HighSchool                 0.828592    117651        str
AssociationFeeFrequency    0.745445    105845        str
SubdivisionName            0.645726     91686        str
MainLevelBedrooms          0.391382     55572    float64
Flooring                   0.355950     50541        str
AssociationFee             0.291283     41359    float64
HighSchoolDistrict         0.269535     38271        str
MLSAreaMajor               0.146561     20810        str
AttachedGarageYN           0.121073     17191     object
Stories                    0.104043     14773    float64
ViewYN                     0.090859     12901     object
PoolPrivateYN              0.077309     10977     object
NewConstructionYN          0.076274     10830     object
Levels                     0.071928     10213        str
GarageSpaces               0.039552      5616    float64
LotSizeSquareFeet          0.017121      2431    float64
StreetNumberNumeric        0.001183       168    float64
UnparsedAddress            0.000972       138        str
FireplaceYN                0.000761       108     object
YearBuilt                  0.000683        97    float64
LivingArea                 0.000549        78    float64
City                       0.000345        49        str
BathroomsTotalInteger      0.000092        13    float64
Latitude                   0.000092        13    float64
Longitude                  0.000092        13    float64
PurchaseContractDate       0.000049         7        str
PostalCode                 0.000014         2        str
ParkingTotal               0.000007         1    float64
ListingKey                 0.000000         0      int64
CloseDate                  0.000000         0        str
ClosePrice                 0.000000         0    float64
PropertyType               0.000000         0        str
MlsStatus                  0.000000         0        str
DaysOnMarket               0.000000         0      int64
ListingContractDate        0.000000         0        str
ContractStatusChangeDate   0.000000         0        str
BedroomsTotal              0.000000         0    float64
ListingId                  0.000000         0        str
ListingKeyNumeric          0.000000         0      int64
CountyOrParish             0.000000         0        str
PropertySubType            0.000000         0        str
StateOrProvince            0.000000         0        str

#### Dealing with Missing Values
- Drop null rows in columns with less than 5 missing values
- Fill NAs in categorical columns with 'Unknown'
- Flag missingness in rows where imputation was used
- Use median imputation or a missingness flag for numerical-categorical columns to preserve datatypes
- Assume that a missing value in a boolean column means False and fill accordingly
- Use median imputation on numerical rows to avoid outlier skew
- Assume missing `AssociationFee`, `GarageSpaces`, and `ParkingTotal` mean 0 and fill accordingly
- Drop columns with 0 values in `ClosePrice`, `LivingArea`, `BathroomsTotalInteger`, and `DaysOnMarket` as a 0 value is highly improbable

In [9]:
# Categorize columns

cat_col = ['Flooring', 'UnparsedAddress', 'AssociationFeeFrequency', 
        'MLSAreaMajor', 'ElementarySchool', 'SubdivisionName', 'City', 
        'PurchaseContractDate', 'MiddleOrJuniorSchool', 'HighSchool',
        'HighSchoolDistrict', 'PostalCode', 'Levels', 'ListingKey', 'CloseDate', 
        'PropertyType', 'ListingKeyNumeric', 'CountyOrParish', 'MlsStatus', 
        'PropertySubType', 'ListingId', 'ContractStatusChangeDate',
        'ListingContractDate', 'StateOrProvince' ]

bool_col = ['ViewYN', 'PoolPrivateYN', 'AttachedGarageYN', 'FireplaceYN', 'NewConstructionYN']

num_col = ['LivingArea', 'LotSizeSquareFeet', 'BathroomsTotalInteger', 
            'Stories', 'MainLevelBedrooms', 'BedroomsTotal', 'DaysOnMarket']

In [10]:
df.shape

(141989, 44)

In [11]:
# Drop outliers that are greater than the 99th percentile of the data

for col in num_col + ['ClosePrice']:
    upper = df[col].quantile(0.99)
    df = df[df[col] <= upper]

df.shape

(80502, 44)

In [12]:
# Drop null rows in columns with a very small number of missing values 
df = df.dropna(subset = ['PostalCode', 'ParkingTotal', 'Longitude', 'Latitude'])

# Fill missing categorical values with 'Unknown'
df[cat_col] = df[cat_col].fillna('Unknown')

# Flag missingness in columns where imputation is used
for col in df.columns:
    if df[col].isna().sum() > 0:
        df[f'{col}_was_missing'] = df[col].isna().astype(int) # 1 for missing, 0 for present

# Handle numerical-categorical columns with median or a specific numeric flag (like -1)
df['YearBuilt'] = df['YearBuilt'].fillna(df['YearBuilt'].median())
df['StreetNumberNumeric'] = df['StreetNumberNumeric'].fillna(-1)

# Convert to boolean type and fill NaNs with False
df[bool_col] = df[bool_col].fillna(False).astype(bool)

# Impute with the median value of the column
for col in num_col:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

# Special case: AssociationFee
# If an association fee is missing, it usually means there is no HOA fee (0.0)
if 'AssociationFee' in df.columns:
    df['AssociationFee'] = df['AssociationFee'].fillna(0.0)

# Fill missing parking/garage counts with 0
for col in ['GarageSpaces', 'ParkingTotal']:
    if col in df.columns:
        df[col] = df[col].fillna(0)

df = df[(df["ClosePrice"]>0) & (df["LivingArea"]>0) & (df["BathroomsTotalInteger"]>0) & (df["DaysOnMarket"]>0)]
df.head()

,Flooring,ViewYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,...,LotSizeSquareFeet,ViewYN_was_missing,PoolPrivateYN_was_missing,AttachedGarageYN_was_missing,YearBuilt_was_missing,StreetNumberNumeric_was_missing,FireplaceYN_was_missing,NewConstructionYN_was_missing,GarageSpaces_was_missing,AssociationFee_was_missing
86,SeeRemarks,False,False,1114319133,2025-05-30,554869.0,33.746904,-117.128111,25483 Calamity Lane,Residential,...,4347.0,0,0,0,0,0,0,0,0,0
104,Laminate,True,False,1114250894,2025-05-30,700000.0,33.479802,-117.069631,33686 Abbey Road,Residential,...,6534.0,0,0,0,0,0,0,0,0,0
106,Carpet,True,False,1114246939,2025-05-28,875000.0,33.622840,-117.641489,28097 CALLE VALDES,Residential,...,4095.0,0,0,0,0,0,0,0,0,0
120,Unknown,True,False,1114212175,2025-05-28,870000.0,34.148868,-117.588025,5847 Zapata Place,Residential,...,20160.0,0,0,0,0,0,0,0,0,0
141,Unknown,True,False,1113976206,2025-05-20,2430000.0,34.123876,-118.104931,2335 Cumberland Road,Residential,...,8804.0,0,0,0,0,0,0,0,0,0

In [21]:
df.isna().sum().sum()

np.int64(0)

#### Encoding Columns
- Convert boolean columns to int values of 0 and 1
- Columns `Flooring` and `Levels` contained lists of values, use MultiLabelBinarizer to encode them
- Map ordinal values of `AssociationFeeFrequency` to their corresponding numerical values
- One hot encode a set of critical categorical columns instead of all to reduce column amount

In [14]:
one_hot = ['CountyOrParish', 'StateOrProvince', 'City', 'PropertyType', 'PropertySubType', 'MlsStatus']
for col in one_hot:
    print(f'{col}: {len(df[col].unique())}')

CountyOrParish: 55
StateOrProvince: 3
City: 764
PropertyType: 1
PropertySubType: 1
MlsStatus: 1

In [15]:
# Encode Boolean columns
encode_df = df.copy()
encode_df[bool_col] = encode_df[bool_col].astype(int)

# Encode 'Flooring' and 'Levels' columns using MultiLabelBinarizer
from sklearn.preprocessing import MultiLabelBinarizer

cols = ['Flooring', 'Levels']
for col in cols:
    encode_df[col] = encode_df[col].str.split(',')
    mlb = MultiLabelBinarizer()
    encoded = pd.DataFrame(mlb.fit_transform(df[col]), columns=[f'{col}_{c}' for c in mlb.classes_], index=df.index)
    encode_df = encode_df.join(encoded)
    encode_df = encode_df.drop(columns = col)

# Map the ordinal values in 'AssociationFeeFrequency' to their associated numerical values
mapping = {
    'Unknown': 0,
    'Monthly': 1,
    'Quarterly': 2,
    'SemiAnnually': 3,
    'Annually': 4
}
encode_df['AssociationFeeFrequency'] = encode_df['AssociationFeeFrequency'].map(mapping)

# One hot encode subset of critical categorical columns, label values that appear less often ass 'Other' to reduct columns
one_hot = ['CountyOrParish', 'StateOrProvince', 'City', 'PropertyType', 'PropertySubType', 'MlsStatus']
for col in one_hot:
    top_values = encode_df[col].value_counts().head(200).index
    encode_df[col] = encode_df[col].apply(lambda x: x if x in top_values else 'Other')
encode_df = pd.get_dummies(encode_df, columns=[col for col in one_hot if col in encode_df.columns], drop_first=True)

df = encode_df
df.head()

,ViewYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,LivingArea,DaysOnMarket,...,City_West Hills,City_Westminster,City_Whittier,City_Wildomar,City_Winchester,City_Winnetka,City_Woodland Hills,City_Yorba Linda,City_Yucaipa,City_Yucca Valley
86,0,0,1114319133,2025-05-30,554869.0,33.746904,-117.128111,25483 Calamity Lane,1858.0,3,...,False,False,False,False,False,False,False,False,False,False
104,1,0,1114250894,2025-05-30,700000.0,33.479802,-117.069631,33686 Abbey Road,2648.0,4,...,False,False,False,False,False,False,False,False,False,False
106,1,0,1114246939,2025-05-28,875000.0,33.622840,-117.641489,28097 CALLE VALDES,1431.0,2,...,False,False,False,False,False,False,False,False,False,False
120,1,0,1114212175,2025-05-28,870000.0,34.148868,-117.588025,5847 Zapata Place,2142.0,5,...,False,False,False,False,False,False,False,False,False,False
141,1,0,1113976206,2025-05-20,2430000.0,34.123876,-118.104931,2335 Cumberland Road,2141.0,1,...,False,False,False,False,False,False,False,False,False,False

#### Standardizing Numerical Values

Looking at our continuous numerical features, the scales vary drastically from one column to the next. Leaving the data with these massive differences in ranges can cause the final model to not make the most accurate predictions. To fix this and boost our overall model performance, I standardized the continuous variables so they're all evaluated on the same scale.

In [16]:
# Standardize continuous numerical columns

from sklearn.preprocessing import StandardScaler

scale = [
    "LivingArea",
    "LotSizeSquareFeet",
    "AssociationFee",
    "DaysOnMarket"
]

scaler = StandardScaler()
df[scale] = scaler.fit_transform(df[scale])
df.head()

,ViewYN,PoolPrivateYN,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,LivingArea,DaysOnMarket,...,City_West Hills,City_Westminster,City_Whittier,City_Wildomar,City_Winchester,City_Winnetka,City_Woodland Hills,City_Yorba Linda,City_Yucaipa,City_Yucca Valley
86,0,0,1114319133,2025-05-30,554869.0,33.746904,-117.128111,25483 Calamity Lane,-0.075059,-0.818892,...,False,False,False,False,False,False,False,False,False,False
104,1,0,1114250894,2025-05-30,700000.0,33.479802,-117.069631,33686 Abbey Road,0.953256,-0.795849,...,False,False,False,False,False,False,False,False,False,False
106,1,0,1114246939,2025-05-28,875000.0,33.622840,-117.641489,28097 CALLE VALDES,-0.630871,-0.841935,...,False,False,False,False,False,False,False,False,False,False
120,1,0,1114212175,2025-05-28,870000.0,34.148868,-117.588025,5847 Zapata Place,0.294614,-0.772807,...,False,False,False,False,False,False,False,False,False,False
141,1,0,1113976206,2025-05-20,2430000.0,34.123876,-118.104931,2335 Cumberland Road,0.293312,-0.864978,...,False,False,False,False,False,False,False,False,False,False

In [17]:
df.shape

(77517, 344)

In [18]:
df.to_csv('../../data/cleaned.csv', index=False)

In [19]:
smaller_df = df.iloc[0:100]
smaller_df.to_csv('02_cleaned.csv', index=False)

In [20]:
# Convert CloseDate to datetime
df['CloseDate'] = pd.to_datetime(df['CloseDate'])
df = df.sort_values('CloseDate').reset_index(drop=True)

# Split dataframe into train and test sets using given window
def get_time_split(data, X_months):
    latest_date = data['CloseDate'].max()
    test_start_date = latest_date - pd.DateOffset(months=1)
    train_start_date = test_start_date - pd.DateOffset(months=X_months)
    test_set = data[data['CloseDate'] >= test_start_date]
    train_set = data[(data['CloseDate'] >= train_start_date) & (data['CloseDate'] < test_start_date)]
    return train_set, test_set

# Create testing and training sets, removing target and 'CloseDate'
train_df, test_df = get_time_split(df, X_months=6)
target = 'ClosePrice'
X_train = train_df.drop(columns=['ClosePrice', 'CloseDate'])
y_train = train_df[target]
X_test = test_df.drop(columns=['ClosePrice', 'CloseDate'])
y_test = test_df[target]

# When modeling, different testing windows will be evaulated
window_options = [3, 6, 12]
for X in window_options:
    train_df, test_df = get_time_split(df, X_months=X)
    
    print(f"--- Experimenting with X = {X} Months ---")
    print(f"Train Date Range: {train_df['CloseDate'].min().strftime('%Y-%m-%d')} to {train_df['CloseDate'].max().strftime('%Y-%m-%d')} ({len(train_df)} rows)")
    print(f"Test Date Range:  {test_df['CloseDate'].min().strftime('%Y-%m-%d')} to {test_df['CloseDate'].max().strftime('%Y-%m-%d')} ({len(test_df)} rows)\n")

--- Experimenting with X = 3 Months ---
Train Date Range: 2026-01-30 to 2026-04-29 (16958 rows)
Test Date Range:  2026-04-30 to 2026-05-31 (6544 rows)

--- Experimenting with X = 6 Months ---
Train Date Range: 2025-10-30 to 2026-04-29 (32801 rows)
Test Date Range:  2026-04-30 to 2026-05-31 (6544 rows)

--- Experimenting with X = 12 Months ---
Train Date Range: 2025-05-01 to 2026-04-29 (70973 rows)
Test Date Range:  2026-04-30 to 2026-05-31 (6544 rows)